### PR TITLE
Update Postman.download.recipe

### PR DESCRIPTION
**Pull request by Daz-wallace**
Modified .download receipt to use new URL on webpage
Fixes Issue #9

### CODE REVIEW

**Comment by macmule** [comment]
bump.. still an issue

**Comment by erikng** [comment]
ping

**Comment by bochoven** [comment]
Could you please merge this url?

**Comment by DevBOFH** [comment]
+1 can we get a merge on this?

**Comment by bochoven** [comment]
It looks like this is an abandoned project. Any one wants to fork this?

**Comment by Daz-wallace** [comment]
If there is no objections, I'll work on adopting these recipes into the @autopkg/datajar-recipes repo this Friday?

**Comment by Daz-wallace** [comment]
Right, all moved over to https://github.com/autopkg/dataJAR-recipes 

Any problems, let me know!

**Comment by barteklk** [comment]
Merged, apologies for delay

@Daz-wallace It would be great to leave these recipes here and not to create a copy.  This will help to keep global list of recipes as clean as we can.  The intention is to keep this repo active.  If you're OK with this, you can be invited to collaborators of this repo

**Comment by macmule** [comment]
@bartekik we’ve created copies already.

That was one month after the PR here & 3 months before your response.

If you’re active now, great! But taking months to respond doesn’t show activity.

**Pull request merged**
